### ISSUE TITLE
Relies on FARGATE - but FARGATE is unavailable in eu-west-2

### ISSUE THREAD

**Issue by Mezzle** [aws-quickstart/quickstart-compliance-uk-official#14]
Fargate is unavailable in the London region, which is where things are going to be deployed to for anything UK-Official

**Comment by chris-d-edwards** [comment]
Just checked for my own sanity, https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ shows that it is available. I have a recollection of a release note for it in early 2019, but I can't find it to confirm the exact date.
